### PR TITLE
Let's make it official.

### PR DESCRIPTION
**Pull request by simonsmh**
* We don't need `TW_USE_LEDS_HAPTICS := true` now.
* We don't need another android.hardware.weaver@1.0.so.

PS:
The LED haptics commit is now merged into the master branch, and this TWRP device tree could be compiled and working without any cherry pick commits.
I think it's time to make it official. Could we make contact with the TWRP team?
Actually, I would like to help you maintain this project, too.

Reference:
https://gerrit.omnirom.org/32804
https://gerrit.omnirom.org/32805

### CODE REVIEW

**Comment by notsyncing** [comment]
Thanks very much for your help! I'm so glad that you are willing to help maintaining it!
With these merges, I think it's ready to make it official. 
I've sent an email to them on their website.

**Comment by Enaunimes** [comment]
Anything stopping this from being official? Just noticed that the twrp tree for dipper, which is based on this one, has been taken as official already.

**Comment by notsyncing** [comment]
I've sent an email to TWRP according to their website, but until now I'm not getting any response from them.

**Comment by Enaunimes** [comment]
Hmm...... Maybe try it in their IRC channel?

**Comment by notsyncing** [comment]
Still no answer from their IRC channel http://webchat.freenode.net/?channels=twrp. Any ideas about how to reach them?

**Comment by mauronofrio** [comment]
You need to wait a bit, if in this week they will not answer you in the email, i will contact them

**Comment by notsyncing** [comment]
Thanks!

**Comment by notsyncing** [comment]
TWRP has forked this repo, and I think official images will be released soon.

**Comment by Enaunimes** [comment]
Finally. Congrats!

**Pull request merged**
