### PR TITLE
Try to fix touch issue

### PR DESCRIPTION
**Pull request by simonsmh**

### CODE REVIEW

**Comment by notsyncing** [comment]
Yesterday I also encountered the non responsive problem, but it happened after I entered the password and decryption succeeded, then stuck at twrp main page. Before I could collect any logs, it rebooted. So I guess it does not relate to the TW_SCREEN_BLANK_ON_BOOT option.

I'll try to reproduce this tonight, and if lucky enough, to get some logs, then we could look into it further.

**Comment by simonsmh** [comment]
https://github.com/simonsmh/android_device_xiaomi_polaris/issues/1

**Comment by notsyncing** [comment]
Ok. I'll make a build tonight.

**Comment by notsyncing** [comment]
One more thing to mention, there are people reporting the same problem with my v3 build, which does not compiled with TW_SCREEN_BLANK_ON_BOOT.

**Comment by simonsmh** [comment]
I know that. Actually we don't need this flag, just have a try.
We should get a log to dig deeper in this bug. Personally I think it is a bug caused by driver.

**Pull request merged**
